### PR TITLE
Change in styling

### PR DESCRIPTION
**Pull request by Roland-Ntwali**

### CODE REVIEW

**Review by calebchris000 — CHANGES_REQUESTED** [review]
# Optional Suggestion.

**Kindly remove any code that is redundant. This is to make sure your code is tidy and maintainable.**

**Happy coding!**

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Invalid

You have submitted a the wrong pull request for the milestone `Portfolio: add a contact form and finish the mobile version`. Kindly resubmit the [original pull request](https://github.com/Roland-Ntwali/Portolio/pull/6) containing the review of the previous reviewer.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by calebchris000** [comment]
@Roland-Ntwali , If submitting a pull request is not an option, please open an issue and include the link to your deployed site and send it to the code reviewer.

**Comment by Roland-Ntwali** [comment]
Deploying is not working for me! 🤦🏽‍♂️

**Pull request merged**
